### PR TITLE
Chris matplotlib pandas mods

### PR DESCRIPTION
**Pull request by choldgraf**
Here are all the changes that I made to the readwrite and matplotlib tutorials. I have also included the "empty" notebooks with most of the input code removed (but with comments retained).  I also cleared the output on both styles of notebooks.

Let me know if this looks OK, or if you wanted me to PR against a different branch/repo.

Also, thank you thank you for covering this.  I really appreciate it (and presumably so do the people who won't get sick because of me :P )

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks Chris. Can you just make it against gh-pages in the main repo? Justin already merged my PR creating the links.

**Comment by choldgraf** [comment]
done - did that work?

**Comment by takluyver** [comment]
Looks like it - I haven't checked the files, but I can see the PR.

**Comment by choldgraf** [comment]
Closing this PR because it's been open for a year, no longer serves a purpose, and I am being OCD trying to close old PRs rather than doing actual work.

**Pull request closed without merging**
